### ISSUE TITLE
Can you add cpu offloading to the pipeline?

### ISSUE THREAD

**Issue by throttlekitty** [baaivision/NOVA#2]
I've tried to run the example code, but on 24gb vram, I OOM at the VAE decode step. We'd lose some time with shuffling the models in and out of ram, but at least the generations could complete at this level of vram.

**Comment by PhyscalX** [comment]
Hi, @throttlekitty 

We have implemented  the ``text_encoder->transformer->vae`` offload policy in the commit ab2523e.
You can now use ``pipe.enable_model_cpu_offload()``

BTW, do not forget to set ``PYTORCH_CUDA_ALLOC_CONF`` to ``"expandable_segments:True"``
This memory allocator is optimized for dynamic shape, and is crucial to compress VAE activations.

**Comment by throttlekitty** [comment]
Thank you very much!
