### ISSUE TITLE
生成视频时，输入prompt_image,视频画面被prompt_image完全覆盖，几乎没多少变化

### ISSUE THREAD

**Issue by junphine** [baaivision/NOVA#4]
如果降低输入promp_image的影响，增加文本的提示力量? guidance_scale设置最低或者最高都没有影响

**Comment by PhyscalX** [comment]
Hi, @junphine 

In this zero-shot I2V task, when image prompt is given, the input caption should detail and accurately describe the motion of the subject to match our training caption (We use EMU2-17B to generate the long video caption). Besides, setting an appropriate motion flow is also important to our training optical flow.

Adjusting ``guidance_scale`` can hardly make differences.

**Comment by junphine** [comment]
Thanks for your reply, I see some movement improvement based on your suggestion.
Another point that needs to be improved is that people's faces distort too much!

**Comment by Bitterdhg** [comment]
@junphine Hi
Thanks for your feedback. The face distortion might be because we lack enough human-related data. We're working on collecting more and better data to train our model further.

**Comment by junphine** [comment]
look foward to！
